#pragma once


//서버 로직에서 공유할 오류코드 일체
enum ServerErrorCode
{
	SERVER_OK	//성공


	//
	, SERVER_INI_OPEN_FAIL
	, SERVER_DB_IP_INVALID
	, SERVER_DB_PORT_INVALID
	, SERVER_DB_DATABASE_INVALID
	, SERVER_DB_USER_INVALID
	, SERVER_DB_PASSWD_INVALID

	, MASTER_IP_INVALID
	, MASTER_PORT_INVALID

	, SERVER_IP_INVALID
	, SERVER_PORT_INVALID
	, GAMESERVER_INVALID_CHANNEL
	, GAMESERVER_INVALID_MAX_USER
	, INI_SERVER_STATUS
	, AVATAR_UPDATE_TIME

	, ERR_SERVER_LOADCONFIG_OPEN
	, ERR_SERVER_LOADCONFIG_APPLICATION_NAME
	, ERR_SERVER_LOADCONFIG_WORLD_PORT
	, ERR_SERVER_LOADCONFIG_LIMIT_USER
	, ERR_SERVER_LOADCONFIG_RECV_UDP_POOL_COUNT
	, ERR_SERVER_LOADCONFIG_SEND_UDP_POOL_COUNT
	, ERR_SERVER_LOADCONFIG_REMOTE_RECV_TCP_POOL_SIZE
	, ERR_SERVER_LOADCONFIG_REMOTE_RECV_UDP_POOL_COUNT

	, ERR_SERVER_UDP_BEGIN
	, ERR_SERVER_TCP_BEGIN
	, ERR_SERVER_REMOTE_SESSION_POOL
	, ERR_SERVER_SAME_UDP_PORT

	, ERR_CLIENT_IS_CONNECTED			//이미 접속중.
	, ERR_CLIENT_IS_CONNECTING			//접속 시도중...
	, ERR_CLIENT_FAIL_BEGIN_TCP			//tcp 연결실패
	, ERR_CLIENT_FAIL_BEGIN_UDP			//udp 연결실패

	, SERVICEMANAGER_TERMINAL_PORT_INVALID
	, SERVICEMANAGER_SERVER_WORKDIR_INVALID
	, SERVICEMANAGER_SERVICE_COUNT
	, SERVICEMANAGER_SERVICE_NAME
	, SERVICEMANAGER_SERVER_TYPE_INVALID

	, FTP_IP_INVALID
	, FTP_PORT_INVALID
	, FTP_USER_INVALID
	, FTP_PASSWD_INVALID
	, FTP_PATH_INVALID

	, DRAGON_MAX_SEARCH_COUNT
	, DRAGON_CURRENT_USERS_UPDATE_TIME
};